# Generated by Django 2.1.5 on 2019-04-11 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, help_text='This is event name that should be unique.', max_length=255, null=True, unique=True)),
                ('event_description', models.CharField(blank=True, help_text='This is event description.', max_length=1255, null=True)),
                ('event_image', models.ImageField(help_text='This is event name that should be unique.', upload_to='event_image')),
                ('added_date', models.DateTimeField(auto_now_add=True, help_text='This is the date and time at which the event is first added to the database.')),
                ('updated_date', models.DateTimeField(auto_now=True, help_text='This is the time and date, the event is last updated')),
                ('event_added_by', models.ForeignKey(help_text='This is the person who have added the event to the database', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, help_text='This is location name that should be unique.', max_length=255, null=True, unique=True)),
                ('location_city', models.CharField(blank=True, help_text='This is location city.', max_length=255, null=True)),
                ('location_state', models.CharField(blank=True, help_text='This is location state.', max_length=255, null=True)),
                ('location_country', models.CharField(blank=True, help_text='This is location country.', max_length=255, null=True)),
                ('location_pin_code', models.CharField(blank=True, help_text='This is pin code of the location.', max_length=20, null=True)),
            ],
        ),
    ]
