# Generated by Django 2.1.5 on 2019-04-22 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_eventbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_recipient', models.CharField(blank=True, help_text="This is the reciepient's name who want to book the event.", max_length=255)),
                ('email_of_recipient', models.CharField(blank=True, help_text="This is the reciepient's email who want to book the event.", max_length=255)),
                ('message_of_recipient', models.CharField(blank=True, help_text='This is the message of recipient that wants to ', max_length=1500)),
                ('location', models.ForeignKey(help_text='This is the location information from the database', on_delete=django.db.models.deletion.CASCADE, to='core.Location')),
            ],
        ),
    ]
